<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="container converter">
    <hr/>
    <div class="row">
        <form action="" method="post" class="form">
            <div class="fieldset">
                <div class="field">
                    <div class="control">
                        <label class="label"><?php echo __('RUB'); ?></label>
                        <input type="text" name="rub" id="rub" class="input-text" required/>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label"><?php echo __('PLN'); ?></label>
                        <input type="text" name="pln" id="pln" class="input-text" disabled/>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="button" class="button action continue primary" id="convert_button">
                            <span><?php echo __('Convert'); ?></span>
                        </button>
                        &nbsp;
                        <div class="loading" style="display: none"><img src="<?php echo $block->getViewFileUrl('Kruzhalin_TestTask::images/loader.gif'); ?>" /></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<?php $postUrl = $block->getUrl('kruzhalin_test/index/ajax'); ?>
<script type="text/javascript">
    require([
            'jquery',
            'mage/translate'
        ],
        function ($) {
            "use strict";
            $(document).ready(function ($) {
                $('#convert_button').click(function () {
                    var rub =  $('#rub').val();
                    if(!rub || !$.isNumeric(rub)){
                        alert($.mage.__('Please enter correct amount for RUB field.'));
                        $('#rub').val('');
                        return;
                    }
                    $('.loading').show();
                    $.ajax({
                        method: "POST",
                        url: "<?php  echo $postUrl;?>",
                        data: {rub: rub}
                    })
                        .done(function (result) {
                            $('.loading').hide();
                            if ($.isNumeric(result)) {
                                $('#pln').val(result);
                            } else {
                                alert($.mage.__('Something were wrong'));
                                console.log(result);
                            }
                        })
                });
            });
        });
</script>